async (page) => {
  await page.reload();
  const waitReady = () => page.getByText('Aperçu de votre boîte', {exact:true}).waitFor({timeout:15000});
  const assert = (ok, text) => { if (!ok) throw new Error(text); };
  await page.getByRole('button',{name:'Réinitialiser les paramètres',exact:true}).click();
  await waitReady();
  await page.getByRole('combobox',{name:'Pièce',exact:true}).selectOption('body');
  await page.getByRole('combobox',{name:'Format',exact:true}).selectOption('3mf');
  await page.getByRole('spinbutton',{name:'Largeur mm',exact:true}).fill('232');
  await page.getByText('Vérifiez les dimensions des pièces',{exact:true}).waitFor();
  await waitReady();
  assert(await page.getByRole('button',{name:'Exporter la boîte',exact:true}).isDisabled(),'Oversized P1S export should be blocked');
  await page.getByRole('button',{name:'Creality K2 260 × 260 × 260 mm',exact:true}).click();
  await page.getByText('Chaque pièce tient sur le plateau utile',{exact:true}).waitFor();
  await waitReady();
  assert(await page.getByRole('button',{name:'Exporter la boîte',exact:true}).isEnabled(),'K2 should accept the 246.8 mm body');
  await page.getByRole('spinbutton',{name:'Poids de l’objet g',exact:true}).fill('');
  await page.getByText('Ajoutez le poids',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Réinitialiser les paramètres',exact:true}).click();
  await page.getByRole('spinbutton',{name:'Largeur mm',exact:true}).fill('150');
  await page.getByRole('spinbutton',{name:'Longueur mm',exact:true}).fill('100');
  await page.getByRole('spinbutton',{name:'Hauteur mm',exact:true}).fill('10');
  await page.getByRole('spinbutton',{name:'Calage par face mm',exact:true}).fill('0');
  await waitReady();
  await page.getByText('J’ai pesé mon envoi fermé',{exact:true}).click();
  await page.getByRole('spinbutton',{name:'Poids total réel, boîte et calage inclus g',exact:true}).fill('99');
  await page.getByText('1.00 CHF',{exact:true}).waitFor();
  await page.getByRole('spinbutton',{name:'Poids total réel, boîte et calage inclus g',exact:true}).fill('100.01');
  await page.getByText('1.40 CHF',{exact:true}).waitFor();
  await waitReady();
  const exported = page.waitForEvent('download');
  await page.getByRole('button',{name:'Exporter la boîte',exact:true}).click();
  const file = await exported;
  await file.saveAs('output/playwright/ui-export.3mf');
  const saved = page.waitForEvent('download');
  await page.getByRole('button',{name:'Enregistrer',exact:true}).click();
  await (await saved).saveAs('output/playwright/project.json');
  await page.getByRole('button',{name:'Réinitialiser les paramètres',exact:true}).click();
  await page.locator('input[type=file]').setInputFiles('output/playwright/project.json');
  await page.getByText('Projet chargé.',{exact:true}).waitFor();
  assert(await page.getByRole('spinbutton',{name:'Largeur mm',exact:true}).inputValue() === '150','Project dimensions must round-trip');
  await page.getByRole('spinbutton',{name:'Largeur mm',exact:true}).fill('151');
  await waitReady();
  assert(await page.getByRole('spinbutton',{name:'Poids total réel, boîte et calage inclus g',exact:true}).inputValue() === '', 'Geometry changes must invalidate a measured weight');
  await page.getByRole('button',{name:'Fermée',exact:true}).click();
  await page.getByRole('button',{name:'Pièces à plat',exact:true}).click();
  await page.getByRole('button',{name:'Vue éclatée',exact:true}).click();
  await page.getByRole('button',{name:'Réinitialiser les paramètres',exact:true}).click();
  await waitReady();
  await page.getByRole('button',{name:'Ouverture',exact:true}).click();
  for (const progress of ['0', '15', '30', '40', '100']) {
    await page.locator('#opening-progress').fill(progress);
    assert(await page.locator('#opening-progress').inputValue() === progress, 'Opening progress must update');
  }
  await page.screenshot({path:'output/playwright/opening-verified.png',fullPage:true});
  await page.getByRole('combobox',{name:'Pièce',exact:true}).selectOption('lid');
  for (const format of ['3mf', 'stl']) {
    await page.getByRole('combobox',{name:'Format',exact:true}).selectOption(format);
    const download = page.waitForEvent('download');
    await page.getByRole('button',{name:'Exporter le couvercle',exact:true}).click();
    await (await download).saveAs(`output/playwright/lid.${format}`);
  }
  await page.locator('input[type=file]').setInputFiles('scripts/fixtures/legacy.boxmaker.json');
  await page.getByText('Projet chargé.',{exact:true}).waitFor();
  await waitReady();
  assert(await page.getByRole('combobox',{name:'Modèle de fermeture',exact:true}).inputValue() === 'legacy','Old projects retain the original geometry');
  assert(await page.getByRole('combobox',{name:'Pièce',exact:true}).locator('option').count() === 3,'Old model retains three pieces');
  await page.getByRole('button',{name:'Réinitialiser les paramètres',exact:true}).click();
  await waitReady();
  await page.screenshot({path:'output/playwright/boxmaker-verified.png',timeout:30000,fullPage:true});
  await page.evaluate(() => { document.documentElement.dataset.smoke = 'PASS'; });
  console.log('PASS: printer boundaries, missing weight, letter rates, STL/3MF downloads, project save/load, legacy compatibility, measured weight invalidation, four view modes and opening slider.');
}
